-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 14:16:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `id` BINARY(36) NOT NULL,
  `product_name_fr` VARCHAR(100) NULL,
  `brands` VARCHAR(100) NULL,
  `nutriscore_grade` VARCHAR(1) NULL,
  `categories_tags` VARCHAR(500) NULL,
  `stores_tags` VARCHAR(255) NULL,
  `packaging_tags` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProducts_UNIQUE` ON `mydb`.`Products` (`id` ASC) VISIBLE;

CREATE INDEX `name` ON `mydb`.`Products` (`product_name_fr` ASC, `nutriscore_grade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stores` (
  `id` BINARY(36) NOT NULL,
  `name` VARCHAR(100) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`Stores` (`id` ASC) VISIBLE;

CREATE INDEX `name` ON `mydb`.`Stores` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `id` BINARY(36) NOT NULL,
  `name` VARCHAR(100) NULL,
  `off_id` VARCHAR(36) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `mydb`.`Categories` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Category_Association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_Category_Association` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_Category_Association` (
  `product_id` BINARY(36) NOT NULL,
  `category_id` BINARY(36) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  CONSTRAINT `fk_product_category_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_product_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `category_fk_idx` ON `mydb`.`Product_Category_Association` (`category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Store_Association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_Store_Association` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_Store_Association` (
  `product_id` BINARY(36) NOT NULL,
  `store_id` BINARY(36) NOT NULL,
  PRIMARY KEY (`product_id`, `store_id`),
  CONSTRAINT `fk_product_store_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_product_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`Stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_store_id_idx` ON `mydb`.`Product_Store_Association` (`store_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Registered_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registered_Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registered_Products` (
  `product_tested` BINARY(36) NOT NULL,
  `product_substitued` BINARY(36) NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`product_tested`, `product_substitued`),
  CONSTRAINT `fk_product_id_tested`
    FOREIGN KEY (`product_tested`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_id_substitued`
    FOREIGN KEY (`product_substitued`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_id_substitued_idx` ON `mydb`.`Registered_Products` (`product_substitued` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
